# please see matrix-full.yml for meaning of each field
build-packages:
- label: ubuntu-22.04
  os: ubuntu-22.04
  package: deb
  check-manifest-suite: ubuntu-22.04-amd64

build-images:
- label: ubuntu
  base-image: ubuntu:22.04
  package: deb
  artifact-from: ubuntu-22.04

smoke-tests:
- label: ubuntu

scan-vulnerabilities:
- label: ubuntu

release-packages:
- label: debian-12
  package: deb
  artifact-from: debian-12
  artifact-version: 12
  artifact-type: debian
  artifact: kong.amd64.deb

release-images:
- label: ubuntu
  package: deb
