# please see matrix-full.yml for meaning of each field
build-packages:
  - label: ubuntu-22.04
    os: ubuntu-22.04
    package: deb
    check-manifest-suite: ubuntu-22.04-amd64
  - label: ubuntu-22.04-arm64
    package: deb
    bazel-args: --platforms=//:generic-crossbuild-aarch64
    check-manifest-suite: ubuntu-22.04-arm64

build-images:
  - label: ubuntu
    base-image: ubuntu:22.04
    package: deb
    artifact-from: ubuntu-22.04
    artifact-from-alt: ubuntu-22.04-arm64
    docker-platforms: linux/amd64, linux/arm64

smoke-tests:
  - label: ubuntu

scan-vulnerabilities:
  - label: ubuntu

release-packages:
  - label: ubuntu-22.04
    package: deb
    artifact-from: ubuntu-22.04
    artifact-version: 22.04
    artifact-type: ubuntu
    artifact: kong.amd64.deb
  - label: ubuntu-22.04-arm64
    package: deb
    artifact-from: ubuntu-22.04-arm64
    artifact-version: 22.04
    artifact-type: ubuntu
    artifact: kong.arm64.deb

release-images:
  - label: ubuntu
    package: deb
