build-packages:
# As a general rule, binaries built on one Linux distro will only
# work on other Linux distros that are the same age or newer.
# Therefore, if we want to make binaries that run on most Linux distros,
# we have to use an old enough distro.

# label: used to distinguish artifacts for later use
# os: docker image if not ubuntu/debian, otherwise ignored
# package: package type
# bazel_args: if set, turn on cross-compilation; make sure its value is a bazel platform
# check-manifest-suite: the check manifest suite as defined in scripts/explain_manifest/config.py

# Ubuntu
- label: ubuntu-20.04
  os: ubuntu-20.04
  package: deb
  check-manifest-suite: ubuntu-20.04-amd64
- label: ubuntu-22.04
  os: ubuntu-22.04
  package: deb
  check-manifest-suite: ubuntu-22.04-amd64
- label: ubuntu-22.04-arm64
  os: ubuntu-22.04
  package: deb
  bazel_args: --platforms=//:generic-crossbuild-aarch64
  check-manifest-suite: ubuntu-22.04-arm64

# Debian
- label: debian-10
  os: ubuntu-22.04
  image: ubuntu:18.04
  package: deb
  check-manifest-suite: ubuntu-18.04-amd64
- label: debian-11
  os: ubuntu-20.04
  package: deb
  check-manifest-suite: ubuntu-20.04-amd64

# CentOS
- label: centos-7
  os: ubuntu-22.04
  image: centos:7
  package: rpm
  check-manifest-suite: el7-amd64

# RHEL
- label: rhel-7
  os: ubuntu-22.04
  image: centos:7
  package: rpm
  check-manifest-suite: el7-amd64

# Amazon Linux
- label: amazonlinux-2
  os: ubuntu-22.04
  image: amazonlinux:2
  package: rpm
  check-manifest-suite: amazonlinux-2-amd64

build-images:
# Only build images for the latest version of each major release.

# label: used as compose docker image label ${github.sha}-${label}
# base-image: docker image to use as base
# package: package type
# artifact-from: label of build-packages to use
# artifact-from-alt: another label of build-packages to use for downloading package (to build multi-arch image)
# docker_platforms: comma separated list of docker buildx platforms to build for

# Ubuntu
- label: ubuntu
  base-image: ubuntu:22.04
  package: deb
  artifact-from: ubuntu-22.04
  artifact-from-alt: ubuntu-22.04-arm64
  docker_platforms: linux/amd64, linux/arm64

# Debian
- label: debian
  base-image: debian:11-slim
  package: deb
  artifact-from: debian-11

# RHEL
- label: rhel
  base-image: registry.access.redhat.com/ubi8
  package: rpm
  artifact-from: rhel-7

smoke-tests:
- label: ubuntu
- label: debian
- label: rhel

scan-vulnerabilities:
- label: ubuntu
- label: debian
- label: rhel

release-packages:
# Ubuntu
- label: ubuntu-20.04
  package: deb
  artifact-from: ubuntu-20.04
  artifact-version: 20.04
  artifact-type: ubuntu
  artifact: kong.amd64.deb
- label: ubuntu-22.04
  package: deb
  artifact-from: ubuntu-22.04
  artifact-version: 22.04
  artifact-type: ubuntu
  artifact: kong.amd64.deb
- label: ubuntu-22.04-arm64
  package: deb
  artifact-from: ubuntu-22.04-arm64
  artifact-version: 22.04
  artifact-type: ubuntu
  artifact: kong.arm64.deb

# Debian
- label: debian-10
  package: deb
  artifact-from: debian-10
  artifact-version: 10
  artifact-type: debian
  artifact: kong.amd64.deb
- label: debian-11
  package: deb
  artifact-from: debian-11
  artifact-version: 11
  artifact-type: debian
  artifact: kong.amd64.deb

# CentOS
- label: centos-7
  package: rpm
  artifact-from: centos-7
  artifact-version: 7
  artifact-type: centos
  artifact: kong.el7.amd64.rpm

# RHEL
- label: rhel-7
  package: rpm
  artifact-from: rhel-7
  artifact-version: 7
  artifact-type: rhel
  artifact: kong.el7.amd64.rpm
- label: rhel-8
  package: rpm
  artifact-from: rhel-7
  artifact-version: 8
  artifact-type: rhel
  artifact: kong.el8.amd64.rpm

# Amazon Linux
- label: amazonlinux-2
  package: rpm
  artifact-from: amazonlinux-2
  artifact-version: 2
  artifact-type: amazonlinux
  artifact: kong.aws2.amd64.rpm
- label: amazonlinux-2023
  package: rpm
  artifact-from: amazonlinux-2
  artifact-version: 2023
  artifact-type: amazonlinux
  artifact: kong.aws2023.amd64.rpm

release-images:
- label: ubuntu
- label: debian
- label: rhel
