build-packages:
# label: used to distinguish artifacts for later use
# image: docker image name if the build is running in side a container
# package: package type
# package-type: the nfpm packaging target, //:kong_{package} target; only used when package is rpm
# bazel-args: additional bazel build flags
# check-manifest-suite: the check manifest suite as defined in scripts/explain_manifest/config.py

  # Amazon Linux
- label: amazonlinux-2
  image: amazonlinux:2
  package: rpm
  package-type: aws2
  check-manifest-suite: amazonlinux-2-amd64

build-images:
# Only build images for the latest version of each major release.

# label: used as compose docker image label ${github.sha}-${label}
# base-image: docker image to use as base
# package: package type
# artifact-from: label of build-packages to use
# artifact-from-alt: another label of build-packages to use for downloading package (to build multi-arch image)
# docker-platforms: comma separated list of docker buildx platforms to build for

# RHEL
- label: rhel
  base-image: registry.access.redhat.com/ubi8
  package: rpm
  package-distro: el8
  artifact-from: rhel-8

smoke-tests:
- label: rhel

scan-vulnerabilities:
- label: rhel

release-packages:
# Amazon Linux
- label: amazonlinux-2
  package: rpm
  artifact-from: amazonlinux-2
  artifact-version: 2
  artifact-type: amazonlinux
  artifact: kong.aws2.amd64.rpm

release-images:
- label: rhel
