# please see matrix-full.yml for meaning of each field
build-packages:
- label: ubuntu-22.04
  os: ubuntu-22.04
  package: deb
- label: ubuntu-22.04-arm64
  os: ubuntu-22.04
  package: deb
  arch: arm64

build-images:
- label: ubuntu
  base-image: ubuntu:22.04
  package: deb
  artifact-from: ubuntu-22.04
  artifact-from-alt: ubuntu-22.04-arm64
  artifact-prefix: kong
  platforms: linux/amd64, linux/arm64

smoke-tests:
- label: ubuntu

scan-vulnerabilities:

release-packages:

release-images:
- label: ubuntu
  package: deb
