# please see matrix-full.yml for meaning of each field
build-packages:
- label: ubuntu-22.04
  os: ubuntu-22.04
  package: deb
  check-manifest-suite: ubuntu-22.04-amd64
- label: rhel-9
  os: ubuntu-22.04
  image: rockylinux:9
  package: rpm
  package-type: el9
  check-manifest-suite: el9-amd64

build-images:
- label: ubuntu
  base-image: ubuntu:22.04
  package: deb
  artifact-from: ubuntu-22.04
- label: rhel
  base-image: registry.access.redhat.com/ubi9
  package: rpm
  artifact-from: rhel-9

smoke-tests:
- label: ubuntu
- label: rhel

scan-vulnerabilities:
- label: ubuntu
- label: rhel

release-packages:

release-images:
- label: ubuntu
  package: deb
- label: rhel
