build-packages:
- label: ubuntu-22.04
  os: ubuntu-22.04
  package: deb
- label: ubuntu-22.04-arm64
  os: ubuntu-22.04
  package: deb
  arch: arm64

build-images:
- label: ubuntu
  base-image: ubuntu:22.04
  package: deb
  artifact-from: ubuntu-22.04
  artifact: kong.deb
- label: ubuntu-arm64
  base-image: ubuntu:22.04
  package: deb
  artifact-from: ubuntu-22.04-arm64
  artifact: kong.deb
  arch: arm64

smoke-tests:
- label: ubuntu

scan-vulnerabilities:

release-packages:

release-images:
- label: ubuntu
  package: deb
