# please see matrix-full.yml for meaning of each field
build-packages:
- label: ubuntu-22.04
  os: ubuntu-22.04
  package: deb
- label: ubuntu-22.04-arm64
  os: ubuntu-22.04
  package: deb
  bazel_platform: ubuntu-22.04-arm64
- label: alpine
  os: ubuntu-22.04
  package: apk
  bazel_platform: alpine-x86_64

build-images:
- label: ubuntu
  base-image: ubuntu:22.04
  package: deb
  artifact-from: ubuntu-22.04
  artifact-from-alt: ubuntu-22.04-arm64
  platforms: linux/amd64, linux/arm64
- label: alpine
  base-image: alpine:3.16
  package: apk
  artifact-from: alpine

smoke-tests:
- label: ubuntu
- label: alpine

scan-vulnerabilities:

release-packages:

release-images:
- label: ubuntu
  package: deb
- label: alpine
  package: apk
