# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 21

# Number of days of inactivity before an Issue or Pull Request with the stale label is closed.
daysUntilClose: 7

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - pinned
  - security

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue/PR has been automatically marked as stale because it has
  not had recent activity.  It will be closed if no further activity
  occurs.  Thank you for your contributions!

# Comment to post when closing a stale Issue or Pull Request.
closeComment: >
  This issue/PR has been automatically closed because it has not seen
  any activity in a long time.  If you still want to pursue this
  patch, please reopen the PR and try to address the issues that were
  discussed to help the decision making process.  Thank you for your
  contributions!
