# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.box = "precise64"
  config.vm.box_url ="http://files.vagrantup.com/precise64.box"
  config.vm.synced_folder "../", "/kong"
  config.vm.provider :virtualbox do |vb|
     vb.memory = 2048
  end
  config.vm.network :forwarded_port, guest: 8000, host: 8000 
  config.vm.network :forwarded_port, guest: 8001, host: 8001
  config.vm.provision "shell", inline: "
    echo 'deb http://debian.datastax.com/community stable main' | tee -a /etc/apt/sources.list.d/cassandra.sources.list
    curl -L http://debian.datastax.com/debian/repo_key | apt-key add -
    apt-get update
    apt-get install wget curl tar make gcc unzip git liblua5.1-0-dev luarocks netcat lua5.1 openssl libpcre3 libpcre3-dev openjdk-7-jdk libcurl4-openssl-dev pkg-config dnsmasq cassandra=2.1.7 -y --force-yes
    echo 'nameserver 10.0.2.3' >> /etc/resolv.conf
    /etc/init.d/cassandra restart
    /kong/dev/setup.sh
    "
end
