-- This software is copyright Kong Inc. and its licensors.
-- Use of the software is subject to the agreement between your organization
-- and Kong Inc. If there is no such agreement, use is governed by and
-- subject to the terms of the Kong Master Software License Agreement found
-- at https://konghq.com/enterprisesoftwarelicense/.
-- [ END OF LICENSE 0867164ffc95e54f04670b5169c09574bdbd9bba ]

local typedefs = require "kong.db.schema.typedefs"
local ngx_null = ngx.null

return {
  name = "kafka-upstream",
  fields = {
    { protocols = typedefs.protocols_http },
    { config = {
        type = "record",
        fields = {
          { bootstrap_servers = { description = "Set of bootstrap brokers in a `{host: host, port: port}` list format.", type = "set",
              elements = {
                type = "record",
                fields = {
                  { host = typedefs.host({ required = true }), },
                  { port = typedefs.port({ required = true }), },
                },
              },
            },
          },
          { topic = { description = "The Kafka topic to publish to.", type = "string", required = true }, },
          { timeout = { description = "Socket timeout in milliseconds.", type = "integer", default = 10000 }, },
          { keepalive = { description = "Keepalive timeout in milliseconds.", type = "integer", default = 60000 }, },
          { keepalive_enabled = { type = "boolean", default = false }, },
          { authentication = {
              type = "record",
              fields = {
                { strategy = { description = "The authentication strategy for the plugin, the only option for the value is `sasl`.", type = "string", required = false, one_of = { "sasl" }} },
                { mechanism = { description = "The SASL authentication mechanism.  Supported options: `PLAIN`, `SCRAM-SHA-256`, or `SCRAM-SHA-512`.", type = "string", required = false, one_of = { "PLAIN",
                                                                              "SCRAM-SHA-256",
                                                                              "SCRAM-SHA-512" }}},
                { tokenauth = { description = "Enable this to indicate `DelegationToken` authentication.", type = "boolean", required = false } },
                { user = { description = "Username for SASL authentication.", type = "string", required = false, encrypted = true, referenceable = true } },
                { password = { description = "Password for SASL authentication.", type = "string", required = false, encrypted = true, referenceable = true } },
              }
            }
          },

          {
            security = {
              type = "record",
              fields = {
                { certificate_id = { description = "UUID of certificate entity for mTLS authentication.", type = "string", uuid = true, required = false } },
                { ssl = { description = "Enables TLS.", type = "boolean", required = false } },
              }
            }
          },

          { forward_method = { description = "Include the request method in the message. At least one of these must be true: `forward_method`, `forward_uri`, `forward_headers`, `forward_body`.", type = "boolean", default = false } },
          { forward_uri = { description = "Include the request URI and URI arguments (as in, query arguments) in the message. At least one of these must be true: `forward_method`, `forward_uri`, `forward_headers`, `forward_body`.", type = "boolean", default = false } },
          { forward_headers = { description = "Include the request headers in the message. At least one of these must be true: `forward_method`, `forward_uri`, `forward_headers`, `forward_body`.", type = "boolean",default = false } },
          { forward_body = { description = "Include the request body in the message. At least one of these must be true: `forward_method`, `forward_uri`, `forward_headers`, `forward_body`.", type = "boolean", default = true } },

          -- TODO change cluster_name to required in 3.0
          { cluster_name = { description = "An identifier for the Kafka cluster. By default, this field generates a random string. You can also set your own custom cluster identifier.  If more than one Kafka plugin is configured without a `cluster_name` (that is, if the default autogenerated value is removed), these plugins will use the same producer, and by extension, the same cluster. Logs will be sent to the leader of the cluster.", type = "string", required = false, auto = true } },

          { producer_request_acks = { description = "The number of acknowledgments the producer requires the leader to have received before considering a request complete. Allowed values: 0 for no acknowledgments; 1 for only the leader; and -1 for the full ISR (In-Sync Replica set).", type = "integer", default = 1, one_of = { -1, 0, 1 }, }, },
          { producer_request_timeout = { description = "Time to wait for a Produce response in milliseconds.", type = "integer", default = 2000 }, },
          { producer_request_limits_messages_per_request = { description = "Maximum number of messages to include into a single producer request.", type = "integer", default = 200 }, },
          { producer_request_limits_bytes_per_request = { description = "Maximum size of a Produce request in bytes.", type = "integer", default = 1048576 }, },
          { producer_request_retries_max_attempts = { description = "Maximum number of retry attempts per single Produce request.", type = "integer", default = 10 }, },
          { producer_request_retries_backoff_timeout = { description = "Backoff interval between retry attempts in milliseconds.", type = "integer", default = 100 }, },
          { producer_async = { description = "Flag to enable asynchronous mode.", type = "boolean", default = true }, },
          { producer_async_flush_timeout = { description = "Maximum time interval in milliseconds between buffer flushes in asynchronous mode.", type = "integer", default = 1000 }, },
          { producer_async_buffering_limits_messages_in_memory = { description = "Maximum number of messages that can be buffered in memory in asynchronous mode.", type = "integer", default = 50000 }, },
        },

        entity_checks = {
          { custom_entity_check = {
              field_sources = { "forward_method", "forward_uri", "forward_headers", "forward_body" },
              fn = function(entity)
                if entity.forward_method or entity.forward_uri
                or entity.forward_headers or entity.forward_body then
                  return true
                end
                return nil, "at least one of these attributes must be true: forward_method, forward_uri, forward_headers, forward_body"
              end
            },
          },
          { custom_entity_check = {
            field_sources = { "authentication" },
            fn = function(entity)
              if entity.authentication.strategy == "sasl" then
                -- SASL PLAIN
                if (entity.authentication.mechanism == "PLAIN" or entity.authentication.mechanism == "SCRAM-SHA-256"
                     or entity.authentication.mechanism == "SCRAM-SHA-512") and
                    (entity.authentication.user == ngx_null or entity.authentication.password == ngx_null) then
                  return nil, "if authentication strategy is SASL and mechanism is PLAIN you have to set user and password"
                end
              end

              return true
            end
            },
          },
        },
      },
    },
  },
}