local cjson = require "cjson"
local http_client = require "kong.tools.http_client"

require "kong.tools.ngx_stub"

describe("HTTP Client", function()

  describe("GET", function()

    it("should return a valid GET response", function()
      local response, status, headers = http_client.get("http://httpbin.org/get", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.args.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

    it("should return a valid GET response under SSL", function()
      local response, status, headers = http_client.get("https://httpbin.org/get", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.args.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

  end)

  describe("POST", function()

    it("should return a valid POST response", function()
      local response, status, headers = http_client.post("http://httpbin.org/post", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.form.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

    it("should return a valid POST response under SSL", function()
      local response, status, headers = http_client.post("https://httpbin.org/post", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.form.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

    it("should return a valid POST multipart response", function()
      local response, status, headers = http_client.post_multipart("http://httpbin.org/post", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.form.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

    it("should return a valid POST multipart response under SSL", function()
      local response, status, headers = http_client.post_multipart("https://httpbin.org/post", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.form.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

  end)

  describe("PUT", function()

    it("should return a valid PUT response", function()
      local response, status, headers = http_client.put("http://httpbin.org/put", {name="Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.json.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

    it("should return a valid PUT response under SSL", function()
      local response, status, headers = http_client.put("https://httpbin.org/put", {name="Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.json.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

  end)

  describe("DELETE", function()

    it("should return a valid DELETE response", function()
      local response, status, headers = http_client.delete("http://httpbin.org/delete", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.args.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

    it("should return a valid DELETE response under SSL", function()
      local response, status, headers = http_client.delete("https://httpbin.org/delete", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.args.name)
      assert.are.equal("pippo", parsed_response.headers.Custom)
    end)

  end)

  describe("OPTIONS", function()

    it("should return a valid OPTIONS response", function()
      local response, status, headers = http_client.options("http://mockbin.com/request", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.queryString.name)
      assert.are.equal("pippo", parsed_response.headers.custom)
    end)

    it("should return a valid OPTIONS response under SSL", function()
      local response, status, headers = http_client.options("http://mockbin.com/request", {name = "Mark"}, {Custom = "pippo"})
      assert.are.equal(200, status)
      assert.truthy(headers)
      assert.truthy(response)
      local parsed_response = cjson.decode(response)
      assert.are.equal("Mark", parsed_response.queryString.name)
      assert.are.equal("pippo", parsed_response.headers.custom)
    end)

  end)

end)
