return [[
# *************************
# * DO NOT EDIT THIS FILE *
# *************************
# This configuration file is auto-generated.
# Any modifications made here will be lost.
[cache]
enabled = true
directory = $(quote(wasmtime_cache_directory))
]]
