version: '3.5'
services:
  postgres:
    image: postgres
    ports:
      - 127.0.0.1::5432
    volumes:
      - postgres-data:/var/lib/posgresql/data
    environment:
      POSTGRES_DBS: kong,kong_tests
      POSTGRES_USER: kong
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 8
    restart: on-failure
    stdin_open: true
    tty: true
  cassandra:
      image: cassandra:3
      ports:
        - 127.0.0.1::7199
        - 127.0.0.1::7000
        - 127.0.0.1::9160
        - 127.0.0.1::9042
      volumes:
        - cassandra-data:/var/lib/cassandra
      healthcheck:
        test: ["CMD", "cqlsh", "-e", "'describe cluster'"]
        interval: 5s
        timeout: 5s
        retries: 8
  redis:
    image: redis
    ports:
      - 127.0.0.1::6379
      - 127.0.0.1::6380
    volumes:
      - redis-data:/data
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
  grpcbin:
    image: moul/grpcbin
    ports:
      - 127.0.0.1::9000
      - 127.0.0.1::9001
  zipkin:
    image: openzipkin/zipkin:2.19
    ports:
      - 127.0.0.1::9411

volumes:
  postgres-data:
  cassandra-data:
  redis-data: