{
 "title": "Kong Vitals Prometheus (official)",
 "description": "Dashboard that graphs metrics exported via Kong Enterprise Vitals Prometheus (https://docs.konghq.com/enterprise/1.3-x/admin-api/vitals/vitals-prometheus-strategy/)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Request",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests/Second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_requests_proxy[1m]))",
     "legendFormat": "$client"
    }
   ]
  },
  {
   "title": "Current Database Availbility",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kong_datastore_reachable)*100/count(kong_datastore_reachable)"
    }
   ]
  },
  {
   "title": "Request Duration - 90th Percentile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_proxy_request_bucket[1m])) by (le))",
     "legendFormat": "kong_latency_proxy"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_upstream_bucket[1m])) by (le))",
     "legendFormat": "kong_latency_upstream"
    }
   ]
  },
  {
   "title": "Requests By Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Requests/Second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_status_code{status_code=~\"[0-9]+\"}[1m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Kong Proxy latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_proxy_request_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_proxy_request_bucket[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_latency_proxy_request_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Admin API Access per minute",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_status{component=\"admin_api\"}[1m])*60) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Admin GUI Access per minute",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_status{component=\"admin_gui\"}[1m])*60) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Shdict Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(kong_shdict_free_space/kong_shdict_capacity) by (shdict)",
     "legendFormat": "{{shdict}}"
    }
   ]
  },
  {
   "title": "Portal API Access per minute",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_status{component=\"portal_api\"}[1m])*60) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Portal GUI Access per minute",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_status{ component=\"portal_gui\"}[1m])*60) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}