#!/usr/bin/env bash

set -e

LOCAL_PATH="$(dirname "$(realpath "$0")")"

check_copyright_header_lua_files() {
  local path="$1"
  local copyright_header="$LOCAL_PATH/COPYRIGHT-HEADER"
  local sha
  sha=$(shasum "$copyright_header" | cut -f1 -d' ')
  local files_missing_copyright_header=()

  shopt -s globstar nullglob
  if [ $? -ne 0 ]; then
    echo "'shopt' command failed ensure to run this on bash 4 or newer."
    exit 1
  fi
  for file in "$path"/**/*.lua; do
    if echo "$file" | grep -qs "distribution/"; then
      # with the adaption of kong-build-tools for kong-ee
      # it was found that these lua files didn't have copyright headers
      # and therefore we are maintaining the status quo for now
      continue; 
    fi
    # Add if not exists
    if ! grep -Fq "$sha" "$file"; then
      files_missing_copyright_header+=("${file#"$path/"}")
    fi
  done

  if [ ${#files_missing_copyright_header[@]} -ne 0 ]; then
    >&2 printf "Lua files missing copyright header:\n"
    for file in "${files_missing_copyright_header[@]}"; do
      >&2 printf "  %s\n" "$file"
    done
    exit 1
  fi
}

check_copyright_header_lua_files "$(realpath "$LOCAL_PATH"/..)"
