#!/usr/bin/env bash

set -e

LOCAL_PATH="$(dirname "$(realpath "$0")")"

check_copyright_header_lua_files() {
  local path="$1"
  local sha
  sha=$(shasum "$LOCAL_PATH/COPYRIGHT-HEADER" | cut -f1 -d ' ' )

  mapfile -t -d '' files \
    < <(git -C "$path" ls-files -z '**/*.lua')

  local missing_header=()

  for file in "${files[@]}"; do
    if ! grep -Fq "$sha" "$file"; then
      missing_header+=("${file#"$path/"}")
    fi
  done

  if (( ${#missing_header[@]} > 0 )); then
    >&2 printf "Lua files missing copyright header:\n"
    >&2 printf "  %s\n" "${missing_header[@]}"
    exit 1
  fi
}

check_copyright_header_lua_files "$(realpath "$LOCAL_PATH"/..)"
