#!/usr/bin/env lua

local utils = require "apenode.tools.utils"
local Migrations = require "apenode.tools.migrations"

local function print_usage()
  print("Usage:")
  print("  create   --conf=[conf] --name=[name] # Create a migration file for configured DAOs")
  print("  migrate  --conf=[conf]               # Migrate to the latest migration available")
  print("  rollback --conf=[conf]               # Rollback the latest executed migration")
  print("  reset    --conf=[conf]               # Rollback all migrations")
  os.exit(1)
end

-- Command
local command = arg[1]

-- Arguments
local opts = {}
opts.name = utils.getopt(arg, "name").name
opts.conf = utils.getopt(arg, "conf").conf
if not opts.conf then
  print_usage()
end

-- Load configuration
local configuration, dao = utils.load_configuration_and_dao(opts.conf)

if command == "create" then
  if not opts.name then
    print_usage()
  end

  Migrations.create(configuration, opts.name, function(interface, file_path, file_name)
    os.execute("mkdir -p "..file_path)
    utils.write_to_file(file_path.."/"..file_name..".lua", interface)
  end)
elseif command == "migrate" then
  dao:migrate(function(migration)
    print(utils.green("✔").." Migrated up to: "..utils.yellow(migration.name))
  end)
elseif command == "rollback" then
  dao:rollback(function(migration)
    print(utils.green("✔").." Rollbacked to: "..utils.yellow(migration.name))
  end)
elseif command == "reset" then
  dao:reset(function(migration)
    print(utils.green("✔").." Rollbacked: "..utils.yellow(migration.name))
  end)
else
  print_usage()
end
