#!/usr/bin/env lua

local utils = require "scripts.utils"

-- Load configuration
local opts = {}
opts.conf = utils.getopt(arg, "conf").conf
opts.drop = utils.getopt(arg, "drop").drop
opts.silent = utils.getopt(arg, "s").s
opts.random = utils.getopt(arg, "random").random

local configuration, dao_properties = utils.load_configuration(opts.conf)

-- Load DAO
local dao_factory = require("apenode.dao."..configuration.database..".factory")
local dao = dao_factory(dao_properties)

-- Drop if exists
dao:drop()

if not opts.silent then
  print(utils.green("✔").." Dropped")
end

if not opts.drop then
  dao:populate(opts.random)
  if not opts.silent then
    print(utils.green("✔").." Populated")
  end
end

dao:close()
