#!/usr/bin/env lua

local utils = require "scripts.utils"
local yaml = require "yaml"

-- Load configuration
local opts = {}
opts.random = utils.getopt(arg, "random").random
opts.conf = utils.getopt(arg, "conf").conf
opts.drop = utils.getopt(arg, "drop").drop

local configuration_file = utils.read_file(opts.conf)

if not configuration_file then
  error("No configuration file at: "..opts.conf)
end

local configuration = yaml.load(configuration_file)

dao_configuration = configuration.databases_available[configuration.database]

if not dao_configuration then
  error("No dao \""..configuration.database.."\" defined in "..opts.conf)
end

-- Load DAO
local dao_factory = require("apenode.dao."..configuration.database)
local dao = dao_factory(dao_configuration.properties)

-- Drop if exists
dao:drop()

if not opts.drop then
  dao:populate(opts.random)
end

dao:close()
