#!/usr/bin/env lua

local utils = require "kong.tools.utils"

local function print_usage()
  print("Usage:")
  print("  seed --conf=[conf] [-s] [-r] # Seed the database")
  print("  drop --conf=[conf] [-s] # Drop the database")
  print("Options:")
  print("  --conf=[conf] Path to configuration")
  print("  -s Random including random data (1000 entities by default)")
  os.exit(1)
end

local function log(str)
  print(str)
end

-- Command
local command = arg[1]

-- Arguments
opts = {}
opts.conf = utils.getopt(arg, "conf").conf
opts.random = utils.getopt(arg, "r").r

-- Load configuration
local configuration, dao = utils.load_configuration_and_dao(opts.conf)

dao:prepare()

if command == "seed" then
  -- Drop if exists
  dao:drop()
  dao:seed(opts.random)
  log(utils.green("✔").." Populated")
elseif command == "drop" then
  dao:drop()
  log(utils.green("✔").." Dropped")
else
  dao:close()
  print_usage()
end

dao:close()
