#!/usr/bin/env lua

local utils = require "apenode.tools.utils"

local function print_usage()
  print("Usage:")
  print("  seed --conf=[conf] [-s] [-r] # Seed the database")
  print("  drop --conf=[conf] [-s] # Drop the database")
  print("Options:")
  print("  --conf=[conf] Path to configuration")
  print("  -s Silent output")
  print("  -s Random including random data (1000 entities by default)")
  os.exit(1)
end

-- Command
local command = arg[1]

-- Arguments
local opts = {}
opts.conf = utils.getopt(arg, "conf").conf
opts.silent = utils.getopt(arg, "s").s
opts.random = utils.getopt(arg, "random").random

-- Load configuration
local configuration, dao_properties = utils.load_configuration(opts.conf)
local dao_factory = require("apenode.dao."..configuration.database..".factory")
local dao = dao_factory(dao_properties)

if command == "seed" then
  -- Drop if exists
  dao:drop()
  dao:populate(opts.random)
  if not opts.silent then
    print(utils.green("✔").." Populated")
  end
elseif command == "drop" then
  dao:drop()
  if not opts.silent then
    print(utils.green("✔").." Dropped")
  end
else
  dao:close()
  print_usage()
end

dao:close()
