local spec_helper = require "spec.spec_helpers"
local uuid = require "lua_uuid"

local env = spec_helper.get_env()
local dao_factory = env.dao_factory
local faker = env.faker

describe("key-auth credentials DAO", function()
  setup(function()
    spec_helper.prepare_db()
  end)

  it("should not insert in DB if consumer does not exist", function()
    -- Without a consumer_id, it's a schema error
    local app_t = {name = "key-auth", config = {key_names = {"apikey"}}}
    local app, err = dao_factory.keyauth_credentials:insert(app_t)
    assert.falsy(app)
    assert.truthy(err)
    assert.True(err.schema)
    assert.are.same("consumer_id is required", err.tbl.consumer_id)

    -- With an invalid consumer_id, it's a FOREIGN error
    local app_t = {key = "apikey123", consumer_id = uuid()}
    local app, err = dao_factory.keyauth_credentials:insert(app_t)
    assert.falsy(app)
    assert.truthy(err)
    assert.True(err.foreign)
    assert.equal("does not exist with value '"..app_t.consumer_id.."'", err.tbl.consumer_id)
  end)

  it("should insert in DB and add generated values", function()
    local consumer_t = faker:fake_entity("consumer")
    local consumer, err = dao_factory.consumers:insert(consumer_t)
    assert.falsy(err)

    local cred_t = {key = "apikey123", consumer_id = consumer.id}
    local app, err = dao_factory.keyauth_credentials:insert(cred_t)
    assert.falsy(err)
    assert.truthy(app.key)
    assert.are.same("apikey123", app.key)
    assert.truthy(app.id)
    assert.truthy(app.created_at)
  end)

  it("should insert an autogenerated key", function()
    local consumer_t = faker:fake_entity("consumer")
    local consumer, err = dao_factory.consumers:insert(consumer_t)
    assert.falsy(err)

    local cred_t = {consumer_id = consumer.id}
    local app, err = dao_factory.keyauth_credentials:insert(cred_t)
    assert.falsy(err)
    assert.truthy(app.key)
    assert.truthy(app.id)
    assert.truthy(app.created_at)
  end)

  it("should find a Credential by public_key", function()
    local rows, err = dao_factory.keyauth_credentials:find_all {
      key = "apikey123"
    }
    assert.falsy(err)
    assert.truthy(rows[1])
    assert.equal("apikey123", rows[1].key)
  end)

  it("should handle empty strings", function()
    local rows, err = dao_factory.keyauth_credentials:find_all {
      key = ""
    }
    assert.falsy(err)
    assert.same({}, rows)
  end)

end)
