name: Changelog Validation

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  validate-changelog:
    name: Validate changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Validate changelogs
        uses: Kong/gateway-changelog@e163d5ce4d698c25d3e131fb2e3fcd7589d8299e # main (node24)
        with:
          files: changelog/unreleased/*/*.yml
