version: '3.5'

services:
  opa:
    image: openpolicyagent/opa:0.44.0-dev-static
    command:
    - "run"
    - "--server"
    - "--tls-private-key-file=/fixture_private.key"
    - "--tls-cert-file=/fixture_public.crt"
    - "--addr=http://0.0.0.0:8181"
    - "--addr=https://0.0.0.0:8282"
    - "/fixture.rego"
    restart: on-failure
    stop_signal: SIGKILL
    ports:
      - "127.0.0.1::8181"
      - "127.0.0.1::8282"
    networks:
      - ${NETWORK_NAME}
    volumes:
    - type: bind
      source: ${PWD}/.pongo/fixture.rego
      target: /fixture.rego
    - type: bind
      source: ${PWD}/.pongo/fixture_private.key
      target: /fixture_private.key
    - type: bind
      source: ${PWD}/.pongo/fixture_public.crt
      target: /fixture_public.crt
