name: Label TEST TEST

on:
  pull_request:

permissions:
  pull-requests: write|read

jobs:
  check_author:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check PR Author Membership
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: check_membership
        run: |
          set +e
          echo ${{ github.actor }}
          gh api orgs/Kong/members --paginate -q '.[].login'

