name: Pull Request Label Checker
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]
jobs:
  check-labels:
    name: prevent merge labels
    runs-on: ubuntu-latest

    steps:
    - name: do-not-merge label found
      run: exit 1
      if: ${{ contains(github.event.*.labels.*.name, 'do not merge') || contains(github.event.*.labels.*.name, 'do-not-merge') }}
