name: Pull Request Label Checker
on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled]
jobs:
  check-labels:
    name: prevent merge labels
    runs-on: ubuntu-latest

    steps:
    - name: dump
      run: |
        echo 1
        echo '${{ toJSON(github.event.*.labels.*.name) }}'
        echo 2
        echo "${{ contains(github.event.*.labels.*.name, 'do not merge')"
      
    - name: do-not-merge label found
      run: exit 1
      if: ${{ contains(github.event.*.labels.*.name, 'pr/do not merge') || contains(github.event.*.labels.*.name, 'DO NOT MERGE') }}
