name: "Pull Request Labeler v2"
on:
  # APIP: PR trigger disabled — not applicable to fork
  workflow_dispatch:

jobs:
  labeler:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
