name: Check Repo Actions Status

on:
  pull_request:
    branches:
      - master

jobs:
  check_status:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Check Action Status
        env:
          GH_TOKEN: ${{ secrets.COMMUNITY_PRS_TOKEN }}
        run: |
          REPOS=$(yq e '.repos | join(" ")' .github/repos.yml)

          processed_names=""
          temp_file=$(mktemp)
          
          for repo in ${REPOS[@]}
          do
            echo "Checking $repo ..."
            sha=`curl -s -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$repo/commits|jq -r '.[0].sha'`
            
            curl -s -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28"  \
              "https://api.github.com/repos/$repo/actions/runs?head_branch=master&head_sha=$sha" \
              |jq -r '.workflow_runs|map({name: .name, status: .status, created_at: .created_at}) | sort_by(.created_at) | reverse' \
              |jq -r '.[]| "\(.name),\(.status),\(.created_at)"' \
              | while IFS=',' read -r name status create_at;
              do
                if [[ ! "$processed_names" =~ "$repo-$name" ]]; then
                  processed_names+=" $repo-$name"
                  if [[ "$status" != "completed" ]]; then
                    printf "[%s| %s] (Create At: %s): %s\r\n" "$repo" "$name" "$create_at" "$status" >> $temp_file
                  fi
                fi
              done
          done
          content=`cat $temp_file`
          if [ -n "$content" ]; then
            echo $content
            exit 1
          fi
