name: Spell Check

on: [pull_request]

jobs:
  test:
    name: spelling checker
    runs-on: ubuntu-latest
    steps:
      - name: Checking out source code
        uses: actions/checkout@v3

      - name: Installing codespell
        run: |
          pip install codespell==2.2.1

      - name: Checking misspelling
        run: |
          git grep --cached -il '' | xargs codespell -c -I .github/codespell/.ignore_words.txt -x .github/codespell/.ignore_lines.txt -S *.key,*.crt,COPYRIGHT -D - -D .github/codespell/.dictionary.txt
