name: Test Label AAAAAA

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  check_author:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Label Community PR
        env:
          GH_TOKEN: ${{ secrets.COMMUNITY_PRS_TOKEN }}
          LABEL: "author/community"
          BOTS: "team-gateway-bot app/dependabot"
        run: |
          set +e
          echo "---members---"
          gh api orgs/Kong/members --paginate -q '.[].login'
          echo "---members end---"
          for id in `gh pr list -S 'draft:false' -s 'open'|awk '{print $1}'`
          do
            name=`gh pr view $id --json author -q '.author.login'`
            ret=`gh api orgs/Kong/members --paginate -q '.[].login'|grep "^${name}$"`
            if [[ -z $ret && ! "${BOTS[@]}" =~ $name ]]; then
              echo "add label $name $id $ret"
              gh api orgs/Kong/members --paginate -q '.[].login'|grep "^${name}$"
            else
              echo "remove label $name $id $ret"
              gh api orgs/Kong/members --paginate -q '.[].login'|grep "^${name}$"
            fi
            echo ""
          done
