name: Test Label AAAAAA

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  check_author:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Label Community PR
        env:
          GH_TOKEN: ${{ secrets.COMMUNITY_PRS_TOKEN }}
          LABEL: "author/community"
          BOTS: "team-gateway-bot dependabot"
        run: |
          set +e
          for id in `gh pr list -S 'draft:false' -s 'open'|awk '{print $1}'`
          do
            name=`gh pr view $id --json author -q '.author.login'`
            gh api orgs/Kong/members --paginate -q '.[].login'|grep -q "^${name}$"
            if [[ $? -ne 0 && ! "${BOTS[@]}" =~ $name ]]; then
              echo "add label $name $id"
            else
              echo "remove label $name $id"
            fi
          done
